INSERT INTO ydm_perfume VALUES 
  (DEFAULT, 'Ardent Rose', 'Por fases', 'Mujer', 'Adulto'),
  (DEFAULT, 'A l’Eau de Rosée', 'Por fases', 'Unisex', 'Atemporal'),
  (DEFAULT, '1770', 'Por fases', 'Hombre', 'Adulto');

INSERT INTO ydm_criterio_eval VALUES
(DEFAULT, 'Ubicación geográfica', 'Ubicacion cercana|', 1),
(DEFAULT, 'Costo', 'Bajos costos', 2),
(DEFAULT, 'Alternativa de envío', 'Varias alternativas de envio', 4),
(DEFAULT, 'Condición de pago', 'Flexibilidad de pago', 1),
(DEFAULT, 'Cumplimiento', 'cumple lineamientos de contrato', 2),
(DEFAULT, 'Ubicación geográfica', 'Ubicacion cercana|', 9),
(DEFAULT, 'Costo', 'Bajos costos', 6),
(DEFAULT, 'Alternativa de envío', 'Varias alternativas de envio', 4),
(DEFAULT, 'Condición de pago', 'Flexibilidad de pago', 1);


INSERT INTO ydm_pais VALUES
  (DEFAULT, 'Afganistán'),
  (DEFAULT, 'Albania'),
  (DEFAULT, 'Alemania'),
  (DEFAULT, 'Andorra'),
  (DEFAULT, 'Angola'),
  (DEFAULT, 'Antigua y Barbuda'),
  (DEFAULT, 'Arabia Saudita'),
  (DEFAULT, 'Argelia'),
  (DEFAULT, 'Argentina'),
  (DEFAULT, 'Armenia'),
  (DEFAULT, 'Australia'),
  (DEFAULT, 'Austria'),
  (DEFAULT, 'Azerbaiyán'),
  (DEFAULT, 'Bahamas'),
  (DEFAULT, 'Bangladés'),
  (DEFAULT, 'Barbados'),
  (DEFAULT, 'Baréin'),
  (DEFAULT, 'Bélgica'),
  (DEFAULT, 'Belice'),
  (DEFAULT, 'Benín'),
  (DEFAULT, 'Bielorrusia'),
  (DEFAULT, 'Birmania'),
  (DEFAULT, 'Bolivia'),
  (DEFAULT, 'Bosnia y Herzegovina'),
  (DEFAULT, 'Botsuana'),
  (DEFAULT, 'Brasil'),
  (DEFAULT, 'Brunéi'),
  (DEFAULT, 'Bulgaria'),
  (DEFAULT, 'Burkina Faso'),
  (DEFAULT, 'Burundi'),
  (DEFAULT, 'Bután'),
  (DEFAULT, 'Cabo Verde'),
  (DEFAULT, 'Camboya'),
  (DEFAULT, 'Camerún'),
  (DEFAULT, 'Canadá'),
  (DEFAULT, 'Catar'),
  (DEFAULT, 'Chad'),
  (DEFAULT, 'Chile'),
  (DEFAULT, 'China'),
  (DEFAULT, 'Chipre'),
  (DEFAULT, 'Ciudad del Vaticano'),
  (DEFAULT, 'Colombia'),
  (DEFAULT, 'Comoras'),
  (DEFAULT, 'Corea del Norte'),
  (DEFAULT, 'Corea del Sur'),
  (DEFAULT, 'Costa de Marfil'),
  (DEFAULT, 'Costa Rica'),
  (DEFAULT, 'Croacia'),
  (DEFAULT, 'Cuba'),
  (DEFAULT, 'Dinamarca'),
  (DEFAULT, 'Dominica'),
  (DEFAULT, 'Ecuador'),
  (DEFAULT, 'Egipto'),
  (DEFAULT, 'El Salvador'),
  (DEFAULT, 'Emiratos Árabes Unidos'),
  (DEFAULT, 'Eritrea'),
  (DEFAULT, 'Eslovaquia'),
  (DEFAULT, 'Eslovenia'),
  (DEFAULT, 'España'),
  (DEFAULT, 'Estados Unidos'),
  (DEFAULT, 'Estonia'),
  (DEFAULT, 'Etiopía'),
  (DEFAULT, 'Filipinas'),
  (DEFAULT, 'Finlandia'),
  (DEFAULT, 'Fiyi'),
  (DEFAULT, 'Francia'),
  (DEFAULT, 'Gabón'),
  (DEFAULT, 'Gambia'),
  (DEFAULT, 'Georgia'),
  (DEFAULT, 'Ghana'),
  (DEFAULT, 'Granada'),
  (DEFAULT, 'Grecia'),
  (DEFAULT, 'Guatemala'),
  (DEFAULT, 'Guyana'),
  (DEFAULT, 'Guinea-Conakri'),
  (DEFAULT, 'Guinea-Bisáu'),
  (DEFAULT, 'Guinea Ecuatorial'),
  (DEFAULT, 'Haití'),
  (DEFAULT, 'Honduras'),
  (DEFAULT, 'Hungría'),
  (DEFAULT, 'India'),
  (DEFAULT, 'Indonesia'),
  (DEFAULT, 'Irak'),
  (DEFAULT, 'Irán'),
  (DEFAULT, 'Irlanda'),
  (DEFAULT, 'Islandia'),
  (DEFAULT, 'Islas Marshall'),
  (DEFAULT, 'Islas Salomón'),
  (DEFAULT, 'Israel'),
  (DEFAULT, 'Italia'),
  (DEFAULT, 'Jamaica'),
  (DEFAULT, 'Japón'),
  (DEFAULT, 'Jordania'),
  (DEFAULT, 'Kazajistán'),
  (DEFAULT, 'Kenia'),
  (DEFAULT, 'Kirguistán'),
  (DEFAULT, 'Kiribati'),
  (DEFAULT, 'Kuwait'),
  (DEFAULT, 'Laos'),
  (DEFAULT, 'Lesoto'),
  (DEFAULT, 'Letonia'),
  (DEFAULT, 'Líbano'),
  (DEFAULT, 'Liberia'),
  (DEFAULT, 'Libia'),
  (DEFAULT, 'Liechtenstein'),
  (DEFAULT, 'Lituania'),
  (DEFAULT, 'Luxemburgo'),
  (DEFAULT, 'Macedonia del Norte'),
  (DEFAULT, 'Madagascar'),
  (DEFAULT, 'Malasia'),
  (DEFAULT, 'Malaui'),
  (DEFAULT, 'Maldivas'),
  (DEFAULT, 'Malí'),
  (DEFAULT, 'Malta'),
  (DEFAULT, 'Marruecos'),
  (DEFAULT, 'Mauricio'),
  (DEFAULT, 'Mauritania'),
  (DEFAULT, 'México'),
  (DEFAULT, 'Micronesia'),
  (DEFAULT, 'Moldavia'),
  (DEFAULT, 'Mónaco'),
  (DEFAULT, 'Mongolia'),
  (DEFAULT, 'Montenegro'),
  (DEFAULT, 'Mozambique'),
  (DEFAULT, 'Namibia'),
  (DEFAULT, 'Nauru'),
  (DEFAULT, 'Nepal'),
  (DEFAULT, 'Nicaragua'),
  (DEFAULT, 'Níger'),
  (DEFAULT, 'Nigeria'),
  (DEFAULT, 'Noruega'),
  (DEFAULT, 'Nueva Zelanda'),
  (DEFAULT, 'Omán'),
  (DEFAULT, 'Países Bajos'),
  (DEFAULT, 'Pakistán'),
  (DEFAULT, 'Palaos'),
  (DEFAULT, 'Panamá'),
  (DEFAULT, 'Papúa Nueva Guinea'),
  (DEFAULT, 'Paraguay'),
  (DEFAULT, 'Perú'),
  (DEFAULT, 'Polonia'),
  (DEFAULT, 'Portugal'),
  (DEFAULT, 'Reino Unido'),
  (DEFAULT, 'República Centroafricana'),
  (DEFAULT, 'República Checa'),
  (DEFAULT, 'República del Congo'),
  (DEFAULT, 'República Democrática del Congo'),
  (DEFAULT, 'República Dominicana'),
  (DEFAULT, 'República Sudafricana'),
  (DEFAULT, 'Ruanda'),
  (DEFAULT, 'Rumanía'),
  (DEFAULT, 'Rusia'),
  (DEFAULT, 'Samoa'),
  (DEFAULT, 'San Cristóbal y Nieves:'),
  (DEFAULT, 'San Marino'),
  (DEFAULT, 'San Vicente y las Granadinas'),
  (DEFAULT, 'Santa Lucía'),
  (DEFAULT, 'Santo Tomé y Príncipe'),
  (DEFAULT, 'Senegal'),
  (DEFAULT, 'Serbia'),
  (DEFAULT, 'Seychelles'),
  (DEFAULT, 'Sierra Leona'),
  (DEFAULT, 'Singapur'),
  (DEFAULT, 'Siria'),
  (DEFAULT, 'Somalia'),
  (DEFAULT, 'Sri Lanka'),
  (DEFAULT, 'Suazilandia'),
  (DEFAULT, 'Sudán'),
  (DEFAULT, 'Sudán del Sur'),
  (DEFAULT, 'Suecia'),
  (DEFAULT, 'Suiza'),
  (DEFAULT, 'Surinam'),
  (DEFAULT, 'Tailandia'),
  (DEFAULT, 'Tanzania'),
  (DEFAULT, 'Tayikistán'),
  (DEFAULT, 'Timor Oriental'),
  (DEFAULT, 'Togo'),
  (DEFAULT, 'Tonga'),
  (DEFAULT, 'Trinidad y Tobago'),
  (DEFAULT, 'Túnez'),
  (DEFAULT, 'Turkmenistán'),
  (DEFAULT, 'Turquía'),
  (DEFAULT, 'Tuvalu'),
  (DEFAULT, 'Ucrania'),
  (DEFAULT, 'Uganda'),
  (DEFAULT, 'Uruguay'),
  (DEFAULT, 'Uzbekistán'),
  (DEFAULT, 'Vanuatu'),
  (DEFAULT, 'Venezuela'),
  (DEFAULT, 'Vietnam'),
  (DEFAULT, 'Yemen'),
  (DEFAULT, 'Yibuti'),
  (DEFAULT, 'Zambia'),
  (DEFAULT, 'Zimbabue');

INSERT INTO ydm_asociacion_nacional VALUES
  (DEFAULT, 'FFAA - Flavour & Fragrance Association of Australia', 'Asia-Pacífico', 11),
  (DEFAULT, 'FFANZ - Flavour & Fragrance Association of New Zealand', 'Asia-Pacífico', 132),
  (DEFAULT, 'CAFFCI - China Association of Flavor, Fragrance & Cosmetic Industries', 'Asia-Pacífico', 39),
  (DEFAULT, 'AFFI - Asosiasi Flavor dan Fragran Indonesia', 'Asia-Pacífico', 82),
  (DEFAULT, 'JFFMA - Japan Flavor & Fragrance Materials Association', 'Asia-Pacífico', 92),
  (DEFAULT, 'KFFA - Korea Flavor & Fragrance Association', 'Asia-Pacífico', 45),
  (DEFAULT, 'FFAS - Flavor & Fragrance Association Singapore', 'Asia-Pacífico', 163),     
  (DEFAULT, 'Prodarom', 'Europa', 66),
  (DEFAULT, 'DVRH - Deustcher Verband der Riechstoff-Hersteller E.V.', 'Europa', 3),
  (DEFAULT, 'AISPEC - Federchimica Assospecifici', 'Europa', 90),
  (DEFAULT, 'NEA', 'Europa', 134),
  (DEFAULT, 'SAAFFI - South African Association of the Flavour & Fragrance Industry', 'Europa', 149),
  (DEFAULT, 'AEFAA - Asociación Española de Fragancias y Aromas Alimentarios', 'Europa', 59),
  (DEFAULT, 'SFFIA - Swiss Flavour and Fragrance Industry Association', 'Europa', 171),
  (DEFAULT, 'AREP', 'Europa', 182),
  (DEFAULT, 'IFRA UK', 'Europa', 143),
  (DEFAULT, 'CAFEPA - Cámara Argentina de Fabricantes de Productos Aromaticos', 'Latinoamérica', 9),
  (DEFAULT, 'ABIFRA - Associaçao Brasileira das Industrias de Oleos Essenciais, Fragrancias, Aromas', 'Latinoamérica', 26),
  (DEFAULT, 'ACHISAF - Asociación Chilena de Sabores y Fragancias', 'Latinoamérica', 38),
  (DEFAULT, 'CISF - Cámara de la Industria de Sabores y Fragrancias', 'Latinoamérica', 42),
  (DEFAULT, 'ANFPA - Asociación Nacional de Fabricantes de Productos Aromáticos', 'Latinoamérica', 118),
  (DEFAULT, 'Fragrance Creators Association - USA', 'Norteamérica', 60),
  (DEFAULT, 'Fragrance Creators Association - Canada', 'Norteamérica', 35);

INSERT INTO ydm_productor VALUES
  (DEFAULT, 'Robertet Group', 'www.robertet.com', 'vioryl@vioryl.gr', 8),
  (DEFAULT, 'vioryl S.A', 'www.vioryl.gr', 'rgpd@robertet.com', 8),
  (DEFAULT, 'Comimpar', 'www.comimpar.com.ar', 'ventas@comimpar.com.ar', 17),
  (DEFAULT, 'Issey Miyake', 'www.isseymiyakeparfums.com', 'isseymiyakeparfums@isseymiyake.com', 5),
  (DEFAULT, 'CLP Aromas', 'www.cplaromas.com', 'global.sales@cplaromas.com', 16),
  (DEFAULT, 'DROM Fragance', 'www.drom.com', 'dromfragance@dromfragance.com', 22);

INSERT INTO ydm_pi_pdt_env VALUES
  (DEFAULT, 1, 66, 'Envios Productor'),
  (DEFAULT, 1, 171, 'Envios Productor'),
  (DEFAULT, 2, 72, 'Envios Productor'),
  (DEFAULT, 2, 81, 'Envios Productor'),
  (DEFAULT, 3, 9, 'Envios Productor'),
  (DEFAULT, 3, 3, 'Envios Productor'),
  (DEFAULT, 4, 92, 'Envios Productor'),
  (DEFAULT, 5, 143, 'Envios Productor'),
  (DEFAULT, 6, 60, 'Envios Productor');


INSERT INTO ydm_proveedor VALUES
  (DEFAULT, 'Givaudan', 'www.givaudan.com', 'givaudan@givaudan.com', 8, 171),
  (DEFAULT, 'Imperial Fragrances &amp; Flavors Pvt Ltd', 'www.imperialfragrances.com', 'imperial@imperialfragrances.com', 8, 81),
  (DEFAULT, 'Kurt Kitzing', 'www.cosmetic-business.com', 'kurtkitzing@gkurtkitzing.com', 9, 3);

INSERT INTO ydm_datos_pago  VALUES
  (DEFAULT, 'Bank of America', '0189-84987523-4843-7875', 'Transferencia', 1),
  (DEFAULT, 'ID', 'Franquito_Banquito', 'Paypal', 1),
  (DEFAULT, 'Bank of America', '0189-84987523-4843-7875', 'Tarjeta de Credito', 1),
  (DEFAULT, 'Bank of America', '0189-84987523-4843-7875', 'Tarjeta de Debito', 1),
  (DEFAULT, 'BBVA Provincial', '0246-78856877-3214-4896', 'Transferencia', 2),
  (DEFAULT, 'ID', 'Gorge_michael', 'Paypal', 2),
  (DEFAULT, 'BBVA Provincial', '0246-78856877-3214-4896', 'Tarjeta de Credito', 2),
  (DEFAULT, 'BBVA Provincial', '0246-78856877-3214-4896', 'Tarjeta de Debito', 2),
  (DEFAULT, 'BBVA Provincial', '0246-89785699-7569-8771', 'Transferencia', 3);

 INSERT INTO ydm_miembro_ifra VALUES 
  (DEFAULT, '2015/02/12', 'Principal', 'Proveedor', NULL, 1, NULL),
  (DEFAULT, '2014/05/20', 'Secundario', 'Proveedor', NULL, 2, NULL),
  (DEFAULT, '2015/09/15', 'Principal', 'Productor', NULL, NULL, 1),
  (DEFAULT, '2017/01/29', 'Secundario', 'Productor', NULL, NULL, 1),
  (DEFAULT, '2010/09/21', 'Asociación nacional', 'Proveedor', NULL, 3, NULL),
  (DEFAULT, '2011/11/09', 'Asociación nacional', 'Productor', NULL, NULL, 3),
  (DEFAULT, '2012/10/27', 'Asociación nacional', 'Productor', NULL, NULL, 4),
  (DEFAULT, '2013/02/19', 'Asociación nacional', 'Productor', NULL, NULL, 5),
  (DEFAULT, '2010/03/03', 'Asociación nacional', 'Productor', NULL, NULL, 6);

 INSERT INTO ydm_tlf VALUES 
  (DEFAULT, '+41', '8318498', NULL, 1),
  (DEFAULT, '+91', '6475215', NULL, 2),
  (DEFAULT, '+49', '7916538', NULL, 3),
  (DEFAULT, '+33', '4683167', 1, NULL),
  (DEFAULT, '+30', '6895491', 2, NULL),
  (DEFAULT, '+54', '2376199', 3, NULL),
  (DEFAULT, '+81', '9876435', 4, NULL),
  (DEFAULT, '+44', '3562012', 5, NULL),
  (DEFAULT, '+1', '0457616', 6, NULL);


INSERT INTO ydm_escala VALUES
  ('2018/10/15', 1, 10, 1, '2019/10/15'),
  ('2020/07/05', 1, 20, 2, NULL),
  ('2018/02/13', 1, 15, 3, '2019/02/13'),
  ('2016/05/26', 1, 30, 4, '2017/05/26'),
  ('2019/09/23', 1, 10, 5, NULL),
  ('2017/01/28', 1, 20, 6, '2018/01/28'),
  ('2020/02/18', 1, 15, 1, NULL),
  ('2020/03/01', 1, 30, 2, NULL),
  ('2016/07/05', 1, 10, 3, '2017/07/05');

INSERT INTO ydm_eval_crit VALUES
  (DEFAULT, 1, 1, 10, 'Inicial', '2019/10/15'),
  (DEFAULT, 1, 2, 20, 'Inicial', '2019/10/15'),
  (DEFAULT, 1, 3, 40, 'Inicial', '2019/10/15'),
  (DEFAULT, 1, 4, 10, 'Inicial', '2019/10/15'),
  (DEFAULT, 1, 5, 20, 'Inicial', '2019/10/15'),
  (DEFAULT, 2, 6, 45, 'Inicial', '2019/10/15'),
  (DEFAULT, 2, 7, 30, 'Inicial', '2019/10/15'),
  (DEFAULT, 2, 8, 20, 'Inicial', '2019/10/15'),
  (DEFAULT, 2, 9, 5, 'Inicial', '2019/10/15');

INSERT INTO ydm_evaluacion VALUES
  ('2018/10/15', 1, 1, 80, 'Inicial'),
  ('2020/07/05', 2, 2, 75, 'Renovación'),
  ('2018/02/13', 3, 3, 50, 'Renovación'),
  ('2016/05/26', 1, 4, 40, 'Inicial'),
  ('2019/09/23', 2, 5, 70, 'Inicial'),
  ('2017/01/28', 3, 6, 80, 'Inicial'),
  ('2020/02/18', 1, 5, 90, 'Inicial'),
  ('2020/03/01', 2, 1, 60, 'Renovación'),
  ('2016/07/05', 3, 4, 40, 'Renovación');

INSERT INTO ydm_contrato VALUES
  (DEFAULT, '2018/10/15', NULL, NULL, FALSE, 1, 1),
  (DEFAULT, '2019/07/05', NULL, NULL, FALSE, 2, 2),
  (DEFAULT, '2020/07/05', NULL, NULL, FALSE, 2, 2),
  (DEFAULT, '2019/11/08', '2019/11/16', 'Por Tardanza', FALSE, 4, 3),
  (DEFAULT, '2018/10/12', NULL, NULL, TRUE, 3, 3),
  (DEFAULT, '2019/10/12', NULL, NULL, TRUE, 3, 3),
  (DEFAULT, '2020/06/18', NULL, NULL, FALSE, 4, 1),
  (DEFAULT, '2018/12/14', NULL, NULL, FALSE, 3, 2),
  (DEFAULT, '2019/12/14', NULL, NULL, FALSE, 3, 2),
  (DEFAULT, '2019/09/08', '2019/09/20', 'Cambio de Productos', FALSE, 1, 2),
  (DEFAULT, '2020/09/15', NULL, NULL, TRUE, 5, 1),
  (DEFAULT, '2020/07/19', NULL, NULL, TRUE, 6, 2);

INSERT INTO ydm_renueva VALUES
  (DEFAULT, 1, '2020/07/05'),
  (DEFAULT, 5, '2019/10/12'),
  (DEFAULT, 8, '2019/12/14');
  
INSERT INTO ydm_condicion_pago VALUES
  (DEFAULT, 1, 'Contado', NULL, NULL, NULL),
  (DEFAULT, 2, 'Crédito', 2, 50, 6),
  (DEFAULT, 3, 'Crédito', 4, 25, 3),
  (DEFAULT, 1, 'Contado', NULL, NULL, NULL),
  (DEFAULT, 2, 'Crédito', 5, 20, 2),
  (DEFAULT, 3, 'Contado', NULL, NULL, NULL);

INSERT INTO ydm_alt_envio VALUES
  (DEFAULT, 1, 1, 66, 'Avion', 2000, NULL),
  (DEFAULT, 1, 1, 66, 'Barco', 1000, NULL),
  (DEFAULT, 2, 2, 171, 'Avion', 2500, NULL),
  (DEFAULT, 2, 2, 171, 'Barco', 1500, NULL),
  (DEFAULT, 3, 3, 72, 'Avion', 3000, NULL),
  (DEFAULT, 3, 3, 72, 'Barco', 1800, NULL),
  (DEFAULT, 1, 5, 81, 'Avion', 2000, NULL),
  (DEFAULT, 2, 6, 9, 'Barco', 3000, NULL),
  (DEFAULT, 3, 7, 3, 'Barco', 2000, NULL);

INSERT INTO ydm_cond_env_pago VALUES
  (DEFAULT, 1, 'Descripcion', 1, 1, 1, 1, 1, 66),
  (DEFAULT, 2, 'Descripcion', 2, 2, 4, 2, 2, 171),
  (DEFAULT, 3, 'Descripcion', 3, 3, 6, 3, 3, 72),
  (DEFAULT, 4, 'Descripcion', 4, 1, 7, 1, 5, 81),
  (DEFAULT, 5, 'Descripcion', 5, 2, 8, 2, 6, 9),
  (DEFAULT, 6, 'Descripcion', 6, 3, 9, 3, 7, 3);

INSERT INTO ydm_pedido VALUES
  (DEFAULT, '2018/10/18', 20000, 'Confirmado', 1, 1, 1, 1, 1, 1, '2018/10/28', 1),
  (DEFAULT, '2019/07/10', 30000, 'Confirmado', 2, 2, 2, 2, 2, 2, '2019/07/15', 2),
  (DEFAULT, '2020/07/12', 15000, 'Por confirmar', 3, 3, 3, 3, 3, 3, NULL, NULL);

INSERT INTO ydm_pago VALUES
  (DEFAULT, 1, '2018/10/29', 20000),
  (DEFAULT, 2, '2019/08/10', 15000),
  (DEFAULT, 2, '2020/02/20', 15000);
  
    
INSERT INTO ydm_intensidad VALUES 
  (DEFAULT, 1, 'Eau de perfume', '15%'),
  (DEFAULT, 2, 'Eau de cologne', '5%'),
  (DEFAULT, 3, 'Eau de toilette', '8%');

INSERT INTO ydm_familia_olfativa VALUES
  (DEFAULT, 'Verde'),
  (DEFAULT, 'Cítrico'),
  (DEFAULT, 'Flores'),
  (DEFAULT, 'Frutas'),
  (DEFAULT, 'Aromáticos'),
  (DEFAULT, 'Helechos (Fougère)'),
  (DEFAULT, 'Chipre'),
  (DEFAULT, 'Maderas'),
  (DEFAULT, 'Orientales'),
  (DEFAULT, 'Otros');

INSERT INTO ydm_principal VALUES
  (1, 3, TRUE),
  (1, 10, DEFAULT),
  (1, 8, DEFAULT),
  (2, 3, TRUE),
  (2, 1, DEFAULT),
  (2, 4, DEFAULT),
  (2, 10, DEFAULT),
  (3, 8, TRUE),
  (3, 2, DEFAULT),
  (3, 10, DEFAULT);

INSERT INTO ydm_proceso VALUES
  (DEFAULT, 'Maceración', 'Cuando se procede por maceración es necesario colocar las flores en unas grandes calderas manteniéndolas sumergidas a fin de que suelten el olor.'),
  (DEFAULT, 'Expresión', 'Muy conveniente en la cidra, la naranja y la bergamota. Cuando el fruto es abundante, se exprime para recoger el aceite.'),
  (DEFAULT, 'Destilación', 'Se emplea un alambique de cavidad bastante grande. La parte del vegetal que contiene la esencia se machaca y se introduce en el alambique.'),
  (DEFAULT, 'Enfleurage', 'El procedimiento extractivo de disolución sirve para ciertas flores delicadas; utilizando para esto ciertas sustancias grasas que tienen la propiedad de absorber los perfumes por contacto.');

INSERT INTO ydm_esencia_perfume VALUES
  (DEFAULT, 'Magnolia', 'Este es un tipo clásico de magnolia del sur, que se abre con un matiz afrutado, luego conduce a un corazón floral de jazmín, rosa, ylang ylang, azahar, nardo y flor de magnolia, y termina con una nota base suave y almizclada.', 'Natural', DEFAULT, 3),
  (DEFAULT, 'Geranio', 'Una nota media con un fuerte aroma, este geranio tiene un aroma dulce y herbáceo, con algunas notas sutiles similares a la rosa.', 'Natural', '8000-46-2', 3),
  (DEFAULT, 'Rosa Absoluta', 'La rosa es una de las flores más conocidas del mundo, impresionante y exótica tanto en apariencia visual como en aroma.', 'Natural', '8007-01-0', 4),
  (DEFAULT, 'Almizcle', 'Picante y amaderado. Un aroma de almizcle clásico.', 'Sintética', DEFAULT, NULL),
  (DEFAULT, 'Sándalo', 'Una nota base con un aroma medio, el sándalo es oriental y balsámico con un aroma suave, dulce, rico y amaderado.', 'Natural', '8024-35-9', 3),
  (DEFAULT, 'Ámbar', 'Una fragancia muy elegante con un aroma adictivo. Un almizcle delicado y distinto con una nota de ámbar fresco. Un aroma general envolvente.', 'Natural', '8002-67-3', 3),
  (DEFAULT, 'Bergamota', 'El aroma es cítrico, pero afrutado y dulce con una calidad cálida, floral y picante, recuerda a Neroli, dando una nota media de fuerza media.', 'Natural', '89957-91-5', 2),
  (DEFAULT, 'Naranja', 'Una nota media con un aroma medio, el aceite esencial de naranja tiene un olor dulce y cítrico como las cáscaras de naranja de las que deriva, pero más intenso y concentrado.', 'Natural', '8028-48-6', 2),
  (DEFAULT, 'Peonía', 'Un verdadero símbolo de belleza, la peonía es romántica, polvorienta y floral. De lejos, uno de las mejores esencias florales.', 'Natural', DEFAULT, 1),
  (DEFAULT, 'Albahaca', 'La albahaca tiene un aroma dulce, picante y fresco con una leve nota de fondo de madera balsámica y una dulzura duradera que la convierte en una fuerte nota superior.', 'Natural', '8015-73-4', 3),
  (DEFAULT, 'Jengibre', 'Una nota media con un aroma medio, el aceite esencial de jengibre tiene un aroma cálido, especiado y amaderado con un toque de limón y pimienta.', 'Natural', '8007-08-7', 3),
  (DEFAULT, 'Cítricas Varias', 'Una sabrosa delicia cítrica. Notas altas de ozono floral, muguet, verde, naranja, limón y lima. Notas medias de jazmín, rosa, alcanfor y eucalipto. Violeta en la base de la fragancia.', 'Natural', DEFAULT, NULL),
  (DEFAULT, 'Pimienta Negra', 'Una nota media con un aroma medio, el aceite esencial de pimienta negra tiene un aroma fuerte y picante que recuerda ligeramente al árbol de clavo.', 'Natural', '8006-82-4', 3),
  (DEFAULT, 'Chocolate', 'Un delicioso chocolate con leche. Notas altas de mantequilla afrutada y matices de jazmín. Notas medias de chocolate, miel dulce, rosa y semillas de cilantro. Una vainilla cremosa y polvo en la base.', 'Sintética', DEFAULT, 4),
  (DEFAULT, 'Amaderadas Varias', 'Notas de fragancia que provienen de materiales leñosos (árboles en su mayoría, así como algunos arbustos, como pachulí, o algunas hierbas, como vetiver).', 'Natural', DEFAULT, NULL),
  (DEFAULT, 'Florales Varias', 'Notas florales esenciales en casi todos los perfumes.', 'Natural', DEFAULT, NULL),
  (DEFAULT, 'Pachulí', 'Una nota base con un aroma medio, el pachulí tiene un aroma terroso con ligeras notas afrutadas.', 'Natural', '8014-09-3', 3),
  (DEFAULT, 'Musgo', 'Esta nota base tiene un aroma terroso y similar a la corteza con una consistencia espesa que se usa a menudo en mezclas de perfumes por sus cualidades fijadoras.', 'Natural', '9000-50-4', 4),
  (DEFAULT, 'Vetiver', 'Una nota base con un aroma fuerte, tiene un aroma terroso y amaderado característico de los aceites derivados de las raíces, con una nota rica que es popular en productos diseñados para hombres.', 'Natural', '8016-96-4', 3);

INSERT INTO ydm_nota VALUES
  (DEFAULT, 1, 1, 'Salida'),
  (DEFAULT, 1, 2, 'Salida'),
  (DEFAULT, 1, 3, 'Corazón'),
  (DEFAULT, 1, 4, 'Fondo'),
  (DEFAULT, 1, 5, 'Fondo'),
  (DEFAULT, 1, 6, 'Fondo'),
  (DEFAULT, 2, 7, 'Salida'),
  (DEFAULT, 2, 8, 'Salida'),
  (DEFAULT, 2, 9, 'Corazón'),
  (DEFAULT, 2, 10, 'Corazón'),
  (DEFAULT, 2, 4, 'Fondo'),
  (DEFAULT, 3, 11, 'Salida'),
  (DEFAULT, 3, 12, 'Salida'),
  (DEFAULT, 3, 13, 'Salida'),
  (DEFAULT, 3, 14, 'Corazón'),
  (DEFAULT, 3, 15, 'Corazón'),
  (DEFAULT, 3, 16, 'Corazón'),
  (DEFAULT, 3, 17, 'Fondo'),
  (DEFAULT, 3, 4, 'Fondo'),
  (DEFAULT, 3, 18, 'Fondo'),
  (DEFAULT, 3, 19, 'Fondo');

INSERT INTO ydm_perfumista VALUES
  (DEFAULT, 'Donna', 'Ramanauskas', 60, 'dramanauskas@robertetusa.com', DEFAULT, DEFAULT),
  (DEFAULT, 'Mathieu', 'Nardin', 66, 'mnardin@mane.com', DEFAULT, DEFAULT),
  (DEFAULT, 'Jean', 'Mignon', 66, 'jcmignon@robertetfr.com', 'Charles', DEFAULT);

INSERT INTO ydm_pfm_pfmt VALUES
  (1,1),
  (2,2),
  (3,3);

